modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"
[[mods]]
modId="compressbutton"
version="${file.jarVersion}"
displayName="Quick Compress"
description='''
Adds a button inside the player inventory which you can click on holding an item to compress it.
For example when player holds 18 redstone and clicks the button, then it changes to two blocks.
'''
[[dependencies.compressbutton]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compressbutton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"