modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"
[[mods]]
modId="quickcompress"
version="${file.jarVersion}"
displayName="Quick Compress"
description='''
Allows to quickly compress items using a 3x3 recipe.
'''
[[dependencies.quickcompress]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quickcompress]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"